version: "3.9"
services:
  postgres:
    image: postgres:9.6
    volumes:
      - ./init/roles.sql:/docker-entrypoint-initdb.d/01-roles.sql
      - ./init/db.sql:/docker-entrypoint-initdb.d/02-init.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=p4ssw0rd
